# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('ninetofiver', '0001_initial'), ('ninetofiver', '0002_auto_20161215_1306'), ('ninetofiver', '0003_auto_20161215_1359'), ('ninetofiver', '0004_company_address'), ('ninetofiver', '0005_auto_20161215_1406'), ('ninetofiver', '0006_auto_20161215_1409'), ('ninetofiver', '0007_employmentcontract'), ('ninetofiver', '0008_auto_20161215_1424'), ('ninetofiver', '0009_auto_20161215_1424'), ('ninetofiver', '0010_auto_20161215_1455')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('internal', models.BooleanField(default=False)),
                ('vat_identification_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid VAT identification number', regex='^[A-Z]{2}[a-zA-Z0-9]{2,13}$')])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.company_set+', to='contenttypes.ContentType')),
                ('address', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_country', django_countries.fields.CountryField(max_length=2)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.Company')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.employmentcontract_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
