# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 13:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0002_auto_20161215_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vat_identification_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid VAT identification number', regex='^[A-Z]{2}[a-zA-Z0-9]{2,13}$')]),
        ),
    ]
