# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0002_userrelative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='label',
            new_name='name',
        ),
    ]
