# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0003_auto_20161215_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='foo', max_length=255),
            preserve_default=False,
        ),
    ]
