# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0005_auto_20161215_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
