# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0007_employmentcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentcontract',
            name='ended_at',
            field=models.DateField(null=True),
        ),
    ]
