# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 14:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ninetofiver', '0011_auto_20161224_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityPerformance',
            fields=[
                ('performance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninetofiver.Performance')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.Contract')),
                ('performance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.PerformanceType')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninetofiver.performance',),
        ),
        migrations.CreateModel(
            name='StandbyPerformance',
            fields=[
                ('performance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninetofiver.Performance')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninetofiver.performance',),
        ),
        migrations.AddField(
            model_name='performance',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.performance_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='performance',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.Timesheet'),
        ),
    ]
