# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0013_activityperformance_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninetofiver.Contract')),
                ('day_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ninetofiver.contract',),
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninetofiver.Contract')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninetofiver.contract',),
        ),
        migrations.CreateModel(
            name='SupportContract',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninetofiver.Contract')),
                ('day_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('fixed_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('fixed_fee_period', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, null=True)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ninetofiver.contract',),
        ),
    ]
