# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0017_auto_20161228_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancycontract',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
