# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ninetofiver', '0018_auto_20161228_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.employmentcontracttype_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='employment_contract_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.EmploymentContractType'),
            preserve_default=False,
        ),
    ]
