# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0021_attachment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4, editable=False),
        ),
    ]
