# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0022_auto_20170106_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='uuid',
            new_name='slug',
        ),
    ]
