# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 15:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ninetofiver', '0027_auto_20170215_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours_estimated', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('hours_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.projectestimate_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('description', models.CharField(max_length=255)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.projectextension_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.projectgroup_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.ProjectGroup')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.projectgrouping_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='ends_at',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='starts_at',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='projectgrouping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.ProjectContract'),
        ),
        migrations.AddField(
            model_name='projectextension',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninetofiver.ProjectContract'),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.ProjectContract'),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.ContractRole'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgrouping',
            unique_together=set([('project', 'group')]),
        ),
    ]
