# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 12:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0029_auto_20170216_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectextension',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='projectextension',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='polymorphic_ctype',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='employmentcontracttype',
            options={'ordering': ['label']},
        ),
        migrations.RemoveField(
            model_name='projectestimate',
            name='hours_actual',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_groups',
        ),
        migrations.AlterField(
            model_name='projectestimate',
            name='hours_estimated',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectExtension',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
