# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0031_remove_userrelative_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentcontract',
            name='work_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninetofiver.WorkSchedule'),
        ),
    ]
