# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0032_auto_20170516_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperformance',
            name='contract_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.ContractRole'),
        ),
    ]
