# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0033_activityperformance_contract_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='ninetofiver.Attachment'),
        ),
    ]
