# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0036_auto_20170612_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
