# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0037_userinfo_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='redmine_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='redmine_time_entry_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='redmine_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Became Inuit on'),
        ),
    ]
