# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0039_auto_20170717_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redmineprojectinfo',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='redmineprojectinfo',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='redminetimeentryinfo',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='redminetimeentryinfo',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='redmineuserinfo',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='redmineuserinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='contract',
            name='redmine_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='redmine_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='redmine_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='RedmineProjectInfo',
        ),
        migrations.DeleteModel(
            name='RedmineTimeEntryInfo',
        ),
        migrations.DeleteModel(
            name='RedmineUserInfo',
        ),
    ]
