# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0040_auto_20170717_1256'),
        ('ninetofiver', '0038_auto_20170731_1008'),
    ]

    operations = [
    ]
