# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-10 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0041_merge_20170808_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperformance',
            name='contract',
        ),
        migrations.AddField(
            model_name='performance',
            name='contract',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.Contract'),
            preserve_default=False,
        ),
    ]
