# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0042_auto_20170810_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
