# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-12 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0044_remove_userinfo_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancycontract',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='consultancycontract',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='projectcontract',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='projectcontract',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='supportcontract',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='supportcontract',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='contract',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='starts_at',
            field=models.DateField(default=datetime.date(2017, 9, 12)),
            preserve_default=False,
        ),
    ]
