# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-12 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0045_auto_20170912_1445'),
    ]

    def assign_users_to_group(apps, schema_editor):
        from django.contrib.auth.models import Group
        from django.contrib.auth.models import User
        g, created = Group.objects.get_or_create(name='everyone')
        users = User.objects.all()

        for user in users:
            g.user_set.add(user)


    operations = [
        migrations.RunPython(assign_users_to_group),
    ]