# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0048_auto_20170929_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityperformance',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'base_manager_name': 'base_objects', 'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='consultancycontract',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractgroup',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractrole',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractuser',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employmentcontract',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employmentcontracttype',
            options={'base_manager_name': 'base_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leavedate',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='performancetype',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectcontract',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectestimate',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='standbyperformance',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='supportcontract',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userrelative',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='whereabout',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.AlterModelManagers(
            name='activityperformance',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='attachment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='consultancycontract',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contract',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractgroup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractrole',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contractuser',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employmentcontract',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employmentcontracttype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='holiday',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='leave',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='leavedate',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='leavetype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='performance',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='performancetype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectcontract',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectestimate',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='standbyperformance',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='supportcontract',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timesheet',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userrelative',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='whereabout',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workschedule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contractgroup',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contractrole',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employmentcontracttype',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='performancetype',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='supportcontract',
            name='fixed_fee_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('active', 'Active'), ('pending', 'Pending')], default='active', max_length=16),
        ),
    ]
