# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0049_auto_20180215_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
