# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0051_auto_20180226_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'base_manager_name': 'base_objects', 'ordering': ['id'], 'verbose_name_plural': 'user info'},
        ),
    ]
