# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0052_auto_20180226_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelative',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrelative',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=2, null=True),
        ),
    ]
