# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0054_auto_20180305_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperformance',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
