# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 15:29
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0008_alter_user_username_max_length'),
        ('ninetofiver', '0055_auto_20180309_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninetofiver.Contract')),
                ('contract_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.ContractRole')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.contractusergroup_set+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'base_objects',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contractuser',
            name='contract_user_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninetofiver.ContractUserGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='contractusergroup',
            unique_together=set([('group', 'contract', 'contract_role')]),
        ),
    ]
