# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0056_auto_20180312_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractuser',
            name='contract_user_group',
        ),
        migrations.AddField(
            model_name='contractusergroup',
            name='contract_users',
            field=models.ManyToManyField(editable=False, to='ninetofiver.ContractUser'),
        ),
    ]
