# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0058_auto_20180312_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
