# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import ninetofiver.models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0059_auto_20180314_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=ninetofiver.models.Attachment.generate_file_path),
        ),
    ]
