# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import ninetofiver.models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0060_auto_20180315_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=ninetofiver.models.Company.generate_file_path),
        ),
    ]
