# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0063_auto_20180424_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancetype',
            options={'base_manager_name': 'base_objects', 'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='performancetype',
            name='order',
        ),
    ]
