# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import ninetofiver.models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0066_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(db_index=True, default=ninetofiver.models.ApiKey.generate_key, editable=False, max_length=32),
        ),
    ]
