# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0070_contractuserworkschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(default='Unnamed API key', max_length=255),
            preserve_default=False,
        ),
    ]
