# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0072_auto_20180502_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whereaboutdate',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='whereaboutdate',
            name='timesheet',
        ),
        migrations.RemoveField(
            model_name='whereaboutdate',
            name='whereabout',
        ),
        migrations.RemoveField(
            model_name='whereabout',
            name='user',
        ),
        migrations.AddField(
            model_name='whereabout',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whereabout',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whereabout',
            name='timesheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.Timesheet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WhereaboutDate',
        ),
    ]
