# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 08:21
from __future__ import unicode_literals

import dirtyfields.dirtyfields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ninetofiver', '0074_auto_20180502_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)])),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.Contract')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ninetofiver.contractestimate_set+', to='contenttypes.ContentType')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninetofiver.ContractRole')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'base_objects',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='projectestimate',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='projectestimate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectestimate',
            name='role',
        ),
        migrations.DeleteModel(
            name='ProjectEstimate',
        ),
        migrations.AlterUniqueTogether(
            name='contractestimate',
            unique_together=set([('contract', 'role')]),
        ),
    ]
