# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0076_auto_20180514_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='ninetofiver.Attachment'),
        ),
    ]
