# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0077_timesheet_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='sickness',
            field=models.BooleanField(default=False),
        ),
    ]
