# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0078_auto_20180830_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'base_manager_name': 'base_objects', 'ordering': ['id'], 'permissions': (('receive_pending_leave_reminder', 'Can receive pending leave reminders'),)},
        ),
    ]
