# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-27 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import datetime


def set_date_defaults(apps, schema_editor):
    Performance = apps.get_model('ninetofiver', 'Performance')
    for perf in Performance.objects.all():
        perf.date = datetime.date.today().replace(year=perf.timesheet.year, month=perf.timesheet.month, day=perf.day)
        perf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0079_auto_20180912_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(set_date_defaults),
        migrations.AlterField(
            model_name='performance',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
