# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0080_auto_20180927_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='day',
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(),
        ),
    ]
