# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-05 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0081_auto_20180927_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'base_manager_name': 'base_objects', 'ordering': ['id'], 'permissions': (('receive_modified_attachment_notification', 'Can receive modified attachment notifications'),)},
        ),
    ]
