# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 12:53
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0083_auto_20181008_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperformance',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(24)], verbose_name='Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='consultancycontract',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='contractestimate',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Duration (hours)'),
        ),
    ]
