# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0085_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
