# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0086_auto_20181025_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(max_length=255),
        ),
    ]
